default: &default
  adapter: postgresql
  username: postgres
  password: hearthscr 
  pool: 10

development: 
  <<: *default
  database: leaguepd_development

test: &test
  <<: *default
  encoding: utf8
  database: leaguepd_testing
